apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "73.1.0"
    helm:
      releaseName: monitoring
      valueFiles:
        - values/common.yaml
        - values/onprem.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
