prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    retention: 10d
    # 클러스터 내부 노드(VM1,2,3) 및 앱 자동 수집 설정
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    

grafana:
  service:
    type: NodePort
    nodePort: 32300

  # 비밀번호 설정
  adminPassword: admin123
